# .NET SDK imajý
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

# Çalýþma dizini
WORKDIR /app

# Proje dosyalarýný kopyala
COPY . .

# API klasörüne geç (çünkü .csproj orada)
WORKDIR /app/API

# Restore
RUN dotnet restore

# Build
RUN dotnet publish -c Release -o /app/publish

# Runtime imajý
FROM mcr.microsoft.com/dotnet/aspnet:7.0

WORKDIR /app
COPY --from=build /app/publish .

# Uygulamayý baþlat
ENTRYPOINT ["dotnet", "LibraryManagement.API.dll"]

